# Generated by Django 3.2.6 on 2021-08-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_profile_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
