# Generated by Django 3.2.6 on 2021-08-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_profile_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='submitted',
        ),
    ]
